<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <detailPageRefreshMethod>none</detailPageRefreshMethod>
    <enableCustomizeMyTabs>false</enableCustomizeMyTabs>
    <enableKeyboardShortcuts>true</enableKeyboardShortcuts>
    <enableMultiMonitorComponents>true</enableMultiMonitorComponents>
    <enablePinTabs>true</enablePinTabs>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <keyboardShortcuts>
        <defaultShortcut>
            <action>FOCUS_CONSOLE</action>
            <active>true</active>
            <keyCommand>ESC</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_NAVIGATOR_TAB</action>
            <active>true</active>
            <keyCommand>V</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_DETAIL_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_PRIMARY_TAB_PANEL</action>
            <active>true</active>
            <keyCommand>P</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SUBTAB_PANEL</action>
            <active>true</active>
            <keyCommand>S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FIRST_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SEARCH_INPUT</action>
            <active>true</active>
            <keyCommand>R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_LEFT</action>
            <active>true</active>
            <keyCommand>LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_RIGHT</action>
            <active>true</active>
            <keyCommand>RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>UP_ARROW</action>
            <active>true</active>
            <keyCommand>UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>DOWN_ARROW</action>
            <active>true</active>
            <keyCommand>DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB_SCROLLER_MENU</action>
            <active>true</active>
            <keyCommand>D</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB</action>
            <active>true</active>
            <keyCommand>T</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CLOSE_TAB</action>
            <active>true</active>
            <keyCommand>C</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REFRESH_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>ENTER</action>
            <active>true</active>
            <keyCommand>ENTER</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>EDIT</action>
            <active>true</active>
            <keyCommand>E</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>SAVE</action>
            <active>true</active>
            <keyCommand>CTRL+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CONSOLE_LINK_DIALOG</action>
            <active>false</active>
            <keyCommand>U</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>HOTKEYS_PANEL</action>
            <active>false</active>
            <keyCommand>SHIFT+K</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_MACRO</action>
            <active>false</active>
            <keyCommand>M</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FOOTER_PANEL</action>
            <active>false</active>
            <keyCommand>F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LIST_VIEW</action>
            <active>false</active>
            <keyCommand>SHIFT+N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LEFT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_RIGHT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_TOP_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_BOTTOM_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_APP_LEVEL_COMPONENTS</action>
            <active>false</active>
            <keyCommand>Z</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REOPEN_LAST_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+C</keyCommand>
        </defaultShortcut>
    </keyboardShortcuts>
    <listPlacement>
        <location>full</location>
    </listPlacement>
    <listRefreshMethod>none</listRefreshMethod>
    <saveUserSessions>true</saveUserSessions>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Case</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Knowledge</tab>
    <tab>Employee__c</tab>
    <tab>Resident_D__c</tab>
    <tab>Parent_Residence__c</tab>
    <tab>Candidate__c</tab>
    <tab>Job_Application__c</tab>
    <tab>Postion__c</tab>
    <tab>Merchandise__c</tab>
    <tab>Invoice_Statement__c</tab>
    <tab>Line_Item__c</tab>
    <tab>CEmployee__c</tab>
    <tab>Company__c</tab>
    <tab>Widget__c</tab>
    <tab>Album__c</tab>
    <tab>Track__c</tab>
    <tab>leave_Application__c</tab>
    <tab>investment__c</tab>
    <tab>MC4SF__MC_Interest_Grouping__c</tab>
    <workspaceMappings>
        <mapping>
            <tab>Album__c</tab>
        </mapping>
        <mapping>
            <tab>CEmployee__c</tab>
        </mapping>
        <mapping>
            <tab>Candidate__c</tab>
        </mapping>
        <mapping>
            <tab>Company__c</tab>
        </mapping>
        <mapping>
            <tab>Employee__c</tab>
        </mapping>
        <mapping>
            <tab>Invoice_Statement__c</tab>
        </mapping>
        <mapping>
            <tab>Job_Application__c</tab>
        </mapping>
        <mapping>
            <tab>Line_Item__c</tab>
        </mapping>
        <mapping>
            <tab>MC4SF__MC_Interest_Grouping__c</tab>
        </mapping>
        <mapping>
            <tab>Merchandise__c</tab>
        </mapping>
        <mapping>
            <tab>Parent_Residence__c</tab>
        </mapping>
        <mapping>
            <tab>Postion__c</tab>
        </mapping>
        <mapping>
            <tab>Resident_D__c</tab>
        </mapping>
        <mapping>
            <tab>Track__c</tab>
        </mapping>
        <mapping>
            <tab>Widget__c</tab>
        </mapping>
        <mapping>
            <tab>investment__c</tab>
        </mapping>
        <mapping>
            <tab>leave_Application__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Account</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Case</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Contact</tab>
        </mapping>
        <mapping>
            <tab>standard-Knowledge</tab>
        </mapping>
        <mapping>
            <tab>standard-Lead</tab>
        </mapping>
        <mapping>
            <fieldName>AccountId</fieldName>
            <tab>standard-Opportunity</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
